### ISSUE TITLE
for loop initial declarations

### ISSUE THREAD

**Issue by Kivutar** [libretro/snes9x2002#15]
I get these errors with the latests commits, when building in Lakka: 

    src/gfx.c:3523:10: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
          for (uint32 y = starty; y <= endy; y++)

**Comment by twinaphex** [comment]
I'll change them to C90/C89-compatible.

**Comment by orbea** [comment]
@Kivutar 
Is this still a problem?

**Comment by Kivutar** [comment]
No
